### ISSUE TITLE
mlc-ai-nightly -  Error installing

### ISSUE THREAD

**Issue by Solaxun** [simonw/llm-mlc#11]
Hi Simon - saw your tweet about this library earlier and thought it was too cool, had to try it out.  I'm  having some issues with installing the two dependencies:

`ERROR: Could not find a version that satisfies the requirement mlc-ai-nightly (from versions: none)`

I'm on a M1 Pro.  I also tried going to the [MLC site](https://mlc.ai/package/) to see if maybe they updated the installation instructions - same problem. Wondering if anybody else has run into this yet?

Also unrelated - is this meant to be the successor to `llm-llama-cpp`?

**Comment by Solaxun** [comment]
I should probably ask this in MLC's Issues... moving it there

**Comment by christopherdbull** [comment]
Did you manage to get it installed? I'm hitting the same

**Comment by Solaxun** [comment]
@christopherdbull Yes I did.  I was running an old version of MacOS (several updates behind, Ventura I think it was?).  After upgrading to Sonoma everything worked.  This was a problem I was running into with MLC and it's dependencies, not llm.
